import { useEffect, useState } from 'react';
import { ArrowUpRight, Boxes, CalendarDays, ChartNoAxesCombined, Package, ShoppingBag, Users } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { EmptyState } from '../components/ui/EmptyState';
import { ErrorState } from '../components/ui/ErrorState';
import { LoadingState } from '../components/ui/LoadingState';
import { Badge } from '../components/ui/Badge';
import { getDashboardData, formatCurrency, type DashboardData } from '../services/dataService';

export function DashboardPage() {
  const [data, setData] = useState<DashboardData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void getDashboardData().then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : 'Não foi possível carregar o Dashboard.')).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="dashboard-page"><LoadingState /></div>;
  if (error) return <div className="dashboard-page"><ErrorState message={error} /></div>;
  if (!data) return null;
  const lowStock = [...data.ingredients, ...data.products].filter((item) => item.current_stock <= item.minimum_stock); const revenue = data.sales.reduce((sum, sale) => sum + sale.total, 0); const birthdays = data.customers.filter((customer) => customer.birth_date).slice(0, 5); const today = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full' }).format(new Date());
  const metrics = [{ label: 'Produtos em estoque', value: data.products.length, icon: Package }, { label: 'Insumos em estoque', value: data.ingredients.length, icon: Boxes }, { label: 'Vendas concluídas', value: data.sales.length, icon: ShoppingBag }, { label: 'Clientes cadastrados', value: data.customers.length, icon: Users }];
  return <div className="dashboard-page"><section className="page-heading"><div><p className="eyebrow">{today}</p><h1>Bom dia, Maria.</h1><p className="heading-subtitle">Aqui está um olhar real sobre a sua operação.</p></div><Badge tone="accent">Visão geral</Badge></section><section className="metric-grid" aria-label="Resumo da operação">{metrics.map(({ label, value, icon: Icon }) => <Card key={label} className="metric-card"><div className="metric-icon"><Icon size={20} strokeWidth={1.6} /></div><div><p>{label}</p><strong>{value}</strong><span>{value === 0 ? 'Nenhum registro ainda' : 'Dados do Supabase'}</span></div></Card>)}</section><section className="dashboard-grid"><Card className="wide-card"><div className="card-heading"><div><p className="eyebrow">Movimentação</p><h2>Últimas vendas</h2></div><ArrowUpRight size={19} /></div>{data.sales.length === 0 ? <EmptyState title="Você ainda não possui dados cadastrados." detail="As vendas registradas aparecerão aqui." /> : <div className="dashboard-list">{data.sales.slice(0, 5).map((sale) => <div className="dashboard-list-row" key={sale.id}><span>{new Date(sale.sale_date).toLocaleDateString('pt-BR')}</span><strong>{formatCurrency(sale.total)}</strong></div>)}</div>}</Card><Card className="wide-card"><div className="card-heading"><div><p className="eyebrow">Acompanhe de perto</p><h2>Próximos aniversários</h2></div><CalendarDays size={19} /></div>{birthdays.length === 0 ? <EmptyState title="Nenhum aniversário próximo." detail="Cadastre clientes para acompanhar estas datas." /> : <div className="dashboard-list">{birthdays.map((customer) => <div className="dashboard-list-row" key={customer.id}><span>{customer.name}</span><strong>{new Date(`${customer.birth_date}T12:00:00`).toLocaleDateString('pt-BR')}</strong></div>)}</div>}</Card></section><section className="dashboard-grid lower-grid"><Card className="wide-card"><div className="card-heading"><div><p className="eyebrow">Visão financeira</p><h2>Faturamento válido</h2></div><ChartNoAxesCombined size={19} /></div>{data.sales.length === 0 ? <EmptyState title="Sem movimentação neste período." /> : <div className="dashboard-total"><strong>{formatCurrency(revenue)}</strong><span>Somatório das vendas concluídas carregadas</span></div>}</Card><Card className="wide-card"><div className="card-heading"><div><p className="eyebrow">Atenção necessária</p><h2>Estoque baixo</h2></div><Boxes size={19} /></div>{lowStock.length === 0 ? <EmptyState title="Tudo tranquilo por aqui." detail="Itens com estoque baixo aparecerão nesta lista." /> : <div className="dashboard-list">{lowStock.slice(0, 5).map((item) => <div className="dashboard-list-row" key={item.id}><span>{item.name}</span><strong>{item.current_stock} {item.unit}</strong></div>)}</div>}</Card></section></div>;
}